### ISSUE TITLE
Esta clase es un ValueObject, no una entidad. No debe ir en este carpeta

### ISSUE THREAD

**Issue by maurociancio** [pabliyo/tpencuestasV2#1]
https://github.com/pabliyo/tpencuestasV2/blob/e22e4d1b0383fbdd99198da97123b01af8e6865c/grails-app/domain/tpencuestas3/Vigencia.groovy#L4

Debe ir en src/groovy y persistirla como embedded.

**Comment by Ftejelo** [comment]
y las constraints irian en la Encuesta.groovy ?

**Comment by maurociancio** [comment]
Las constraints pueden ir la vigencia.
