### ISSUE TITLE
Anda esto?

### ISSUE THREAD

**Issue by maurociancio** [pabliyo/tpencuestasV2#16]
https://github.com/pabliyo/tpencuestasV2/blob/1e5b54faf608c5ae6bfb2473681bd1442c3b3a80/grails-app/domain/tpencuestas3/Respuesta.groovy#L8

Anda la persistencia en ese mapa sin declarar como se persiste?

**Comment by pabliyo** [comment]
no, no lo persiste, de hecho eso era lo que le queria preguntar, hice distintos metodos para inicilizarlo, pero igual no persiste. cual seria la manera correcta para que lo persista ?

**Comment by maurociancio** [comment]
Es dudoso un map en el modelo. Se puede hacer segun vi la doc pero no me
acuerdo de memoria.  Busquen otra solución usando colecciones tipos set.

--
Mauro Ciancio
