### ISSUE TITLE
Está ok esto?

### ISSUE THREAD

**Issue by maurociancio** [pabliyo/tpencuestasV2#4]
https://github.com/pabliyo/tpencuestasV2/blob/e22e4d1b0383fbdd99198da97123b01af8e6865c/grails-app/controllers/tpencuestas3/ParticipacionController.groovy#L28

**Comment by pabliyo** [comment]
fue lo que mas costo hasta ahora, creo q ya quedo funcionando. puede que haya alguna desprolijidad pero si lo puede mirar ver algun detalle serviria muchisimo.
