### ISSUE TITLE
Donde están implementadas las historias de usuario?

### ISSUE THREAD

**Issue by maurociancio** [pabliyo/tpencuestasV2#5]
No veo código en las entidades, ni los controladores ni en lo servicios. Donde está?

**Comment by pabliyo** [comment]
ya se puede ver algunos cambios. falta implementar los filtros para mostrar los contenidos dependiendo el rol, cuenta premium y demas. estos filtros estaria bien que los maneje el controlador y los servicios ? gracias.

**Comment by maurociancio** [comment]
Veo el codigo en las entidades que dice `puedoHacerTalCosa` lo cual está bien, pero falta el método `hacerTalCosa` y que falle con excepción si no se puede hacer.
