### ISSUE TITLE
Esto tiene que ser un metodo unico: crear encuesta y si no puede tira excepción. No preguntar para proceder, sino que proceder y fallar si no se puede.

### ISSUE THREAD

**Issue by maurociancio** [pabliyo/tpencuestasV2#7]
https://github.com/pabliyo/tpencuestasV2/blob/2df4848a270fbcb6bd826a69c4fa85afddb8aef3/grails-app/controllers/tpencuestas3/EncuestaController.groovy#L54

**Comment by pabliyo** [comment]
resuelto
